{
 "title": "Tweet app Copy",
 "time": { "from": "2022-08-16T15:34:20.080Z", "to": "2022-08-17T01:43:34.288Z" },
 "refresh": "5s",
 "panels": [
  { "title": "HikariCP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{pool=\"HikariPool-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{pool=\"HikariPool-1\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{pool=\"HikariPool-1\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{pool=\"HikariPool-1\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"tweet-app:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Ready Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 6 },
   "targets": [
    {
     "expr": "application_ready_time_seconds{instance=\"tweet-app:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 6 },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"tweet-app:8081\"}*1000"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Kafka Listener Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "spring_kafka_listener_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Tweet Table Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_count{repository=\"TweetRepository\", method=\"save\", state=\"SUCCESS\"}",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "spring_data_repository_invocations_seconds_count{repository=\"TweetRepository\", method=\"findAll\", state=\"SUCCESS\"}",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "User Table Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_count{method=\"findByUserId\", state=\"SUCCESS\", repository=\"UserRepository\"}",
     "legendFormat": "{{ method }}"
    },
    {
     "expr": "spring_data_repository_invocations_seconds_count{method=\"findAll\", state=\"SUCCESS\", repository=\"UserRepository\"}",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  { "title": "Log levels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Log levels [INFO]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "logback_events_total{level=\"info\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log levels [DEBUG]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "logback_events_total{level=\"debug\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log levels [ERROR]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "logback_events_total{level=\"error\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log levels [WARN]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "targets": [
    {
     "expr": "logback_events_total{level=\"warn\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}